### PR TITLE
Improve window management code

### PR DESCRIPTION
**Pull request by Kaldaien**
## I have fixed numerous issues with the new window management functions:

1. The logic to find the game's main window never times out, and only searches for windows running on the game's main thread

2. ClipCursor (...) is hooked so that no other code can change the rectangle; simply setting or clearing the boundaries on window activation is inadequate to prevent the cursor from slipping out of the window.
3. The mouse boundaries have been shrunken so that the title bar and resize frames are always grabbable.
4. The mouse boundaries are ignored while the user is resizing or dragging the window.
5. The mouse boundaries automatically update if the window is programmatically moved (i.e. Windows+Shift+Left/Right) to a different monitor.

6. `WM_SETFOCUS` and `WM_KILLFOCUS` are used instead of window activation for all things window-focus related.

7. When swallowing window activation in order to prevent the game from muting, pass-through to `DefWindowProc (...)` so that RawInput stops processing mouse input when another window is active.

8. The initialization thread is created suspended so that it does not run to completion before you can even set its priority 😸

### CODE REVIEW

**Comment by Kaldaien** [comment]
I also added an option to disable the screensaver while the game's window is focused.

I -highly- recommend shipping this turned on by default, as the Steam forums are flooded with users complaining about their display entering power saving mode during long cutscenes. Worst of all, when the display is powered back on, the game gives them an "Operation Completed Successfully" error 🤣

**Comment by Lyall** [comment]
That looks great, and works fantastically. Disabling the screensaver is a nice touch!

**Comment by intopuddles** [comment]
> I also added an option to disable the screensaver while the game's window is focused.
> 
> I -highly- recommend shipping this turned on by default, as the Steam forums are flooded with users complaining about their display entering power saving mode during long cutscenes. Worst of all, when the display is powered back on, the game gives them an "Operation Completed Successfully" error 🤣

I just got this in a longer scene without having a screensaver enabled. I went ahead and increased my display inactivity timer from 5min in Windows, which I'm assuming will solve it. Does this merge solve that issue or is it just the screensaver?

**Comment by Zigbigidorlu** [comment]
Excellent! Everything seems to work perfectly.

**Comment by truduEprocEss** [comment]
DisableScreenSaver isn't working for me so I checked the ini and the log.
The FFXVIFix.ini shows:
`; Set "DisableScreensaver" to true to stop your display from going to sleep mid-game.
DisableScreenSaver = true`

The FFXVIFix.log shows:
`[2024-09-21 11:11:53.131] [FFXVIFix.log] [info] Config Parse: bDisableScreensaver: false`

**Comment by Lyall** [comment]
> DisableScreenSaver isn't working for me so I checked the ini and the log. The FFXVIFix.ini shows: `; Set "DisableScreensaver" to true to stop your display from going to sleep mid-game.` `DisableScreenSaver = true`
> 
> The FFXVIFix.log shows: `[2024-09-21 11:11:53.131] [FFXVIFix.log] [info] Config Parse: bDisableScreensaver: false`

Typo on my part, should be fixed in the next build. f4ed0cd

**Comment by Lyall** [comment]
> > I also added an option to disable the screensaver while the game's window is focused.
> > I -highly- recommend shipping this turned on by default, as the Steam forums are flooded with users complaining about their display entering power saving mode during long cutscenes. Worst of all, when the display is powered back on, the game gives them an "Operation Completed Successfully" error 🤣
> 
> I just got this in a longer scene without having a screensaver enabled. I went ahead and increased my display inactivity timer from 5min in Windows, which I'm assuming will solve it. Does this merge solve that issue or is it just the screensaver?
> 
> EDIT: Just got the message again, this time because of alt+tabbing during a paused cutscene lol

It should stop windows from putting the display to sleep, yes.

**Comment by truduEprocEss** [comment]
> > DisableScreenSaver isn't working for me so I checked the ini and the log. The FFXVIFix.ini shows: `; Set "DisableScreensaver" to true to stop your display from going to sleep mid-game.` `DisableScreenSaver = true`
> > The FFXVIFix.log shows: `[2024-09-21 11:11:53.131] [FFXVIFix.log] [info] Config Parse: bDisableScreensaver: false`
> 
> Typo on my part, should be fixed in the next build. [f4ed0cd](https://github.com/Lyall/FFXVIFix/commit/f4ed0cdb5374efcbc586c09d9c65720ba16b6705)

Thanks, Lyall. I saw your fix and corrected it in my ini. It's working now.

**Pull request merged**
